application:
  image: debian:stretch
  volumes:
    - ./:/var/www/website
  tty: true
db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: memory
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db:db
  ports:
    - "8081:80"
  environment:
    - PMA_ARBITRARY=1
  volumes:
    - /sessions
php:
  build: docker/php
  volumes_from:
    - application
  links:
    - db:db
apache:
  image: c2is/debian-apache
  environment:
    - WEBSITE_HOST=localhost
    - VHOST_SUFFIX=app
  ports:
    - "80:80"
    - "443:443"
  links:
    - php
  volumes_from:
    - application